# Generated by Django 5.2.13 on 2026-05-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('pharmacies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.kiosk')),
            ],
            options={
                'db_table': 'ad_impressions',
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(choices=[('0-17', '0-17'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-50', '36-50'), ('51-65', '51-65'), ('65+', '65+')], max_length=8)),
                ('gender', models.CharField(choices=[('F', 'Kadın'), ('M', 'Erkek'), ('O', 'Diğer')], max_length=1)),
                ('is_sensitive_flow', models.BooleanField(default=False)),
                ('qr_code', models.CharField(db_index=True, max_length=64)),
                ('answers_payload', models.JSONField(blank=True, default=dict)),
                ('suggested_ingredients', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='products.category')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='pharmacies.kiosk')),
            ],
            options={
                'db_table': 'session_logs',
                'indexes': [models.Index(fields=['created_at', 'kiosk'], name='session_log_created_ef27af_idx')],
            },
        ),
    ]
