# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamGosterim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('idempotency_anahtari', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gosterilme_tarihi', models.DateTimeField()),
                ('sure_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Reklam Gosterim',
                'verbose_name_plural': 'Reklam Gosterimleri',
                'db_table': 'reklam_gosterimleri',
                'ordering': ('-gosterilme_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='OturumLogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('idempotency_anahtari', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('hassas_akis', models.BooleanField(default=False)),
                ('qr_kodu', models.CharField(db_index=True, max_length=64)),
                ('cevaplar', models.JSONField(blank=True, default=dict)),
                ('onerilen_etken_maddeler', models.JSONField(blank=True, default=list)),
                ('cinsiyet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oturumlar', to='lookups.cinsiyet')),
            ],
            options={
                'verbose_name': 'Oturum Logu',
                'verbose_name_plural': 'Oturum Loglari',
                'db_table': 'oturum_loglari',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
    ]
