# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('lookups', '0001_initial'),
        ('pharmacies', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oturumlogu',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oturumlar', to='products.kategori'),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='kiosk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oturumlar', to='pharmacies.kiosk'),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='yas_araligi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oturumlar', to='lookups.yasaraligi'),
        ),
        migrations.AddField(
            model_name='reklamgosterim',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reklamgosterim',
            name='kiosk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklam_gosterimleri', to='pharmacies.kiosk'),
        ),
        migrations.AddField(
            model_name='reklamgosterim',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reklamgosterim',
            name='reklam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gosterimler', to='campaigns.reklam'),
        ),
        migrations.AddIndex(
            model_name='oturumlogu',
            index=models.Index(fields=['olusturulma_tarihi', 'kiosk'], name='oturum_logl_olustur_fffe65_idx'),
        ),
    ]
