# Generated by Django 5.2.13 on 2026-05-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReklamGosterim',
        ),
    ]
