# Generated by Django 5.2.3 on 2026-06-05 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_oturumlogu_tamamlandi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oturumlogu',
            name='danisma_notu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='danisma_tamamlandi',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='danisma_tamamlanma_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='danisma_tamamlayan_eczaci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamamlanan_danismalar', to=settings.AUTH_USER_MODEL),
        ),
    ]
