# Generated by Django 5.2.16 on 2026-07-31 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_qr_unique_constraint'),
        ('lookups', '0002_remove_il_plaka'),
        ('pharmacies', '0009_kiosk_last_ip'),
        ('products', '0011_alter_danisma_ad_alter_kategori_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oturumlogu',
            name='cihaz_zamani',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kiosk tarafindan bildirilen oturum zamani (cihaz saati).', null=True),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='durum',
            field=models.CharField(choices=[('COMPLETED', 'Tamamlandi'), ('ABANDONED', 'Terk Edildi'), ('EXPIRED', 'Suresi Doldu')], db_index=True, default='COMPLETED', help_text='Oturum durumu: COMPLETED (kullanici bitirdi), ABANDONED (inaktivite/terk), EXPIRED (danisma gerceklesmeyen, sunucu turetimi).', max_length=16),
        ),
        migrations.AddField(
            model_name='oturumlogu',
            name='sunucu_zamani',
            field=models.DateTimeField(blank=True, help_text='Oturumun sunucuya ulastigi an (server clock). cihaz saati yanlis oldugunda referans alinir.', null=True),
        ),
        migrations.AddIndex(
            model_name='oturumlogu',
            index=models.Index(fields=['durum', 'olusturulma_tarihi'], name='oturum_logl_durum_f3c685_idx'),
        ),
        migrations.AddIndex(
            model_name='oturumlogu',
            index=models.Index(fields=['kiosk', 'durum'], name='oturum_logl_kiosk_i_57861d_idx'),
        ),
        migrations.AddIndex(
            model_name='oturumlogu',
            index=models.Index(fields=['cihaz_zamani'], name='oturum_logl_cihaz_z_877d6d_idx'),
        ),
    ]
