# Generated by Django 5.2.16 on 2026-07-31 22:32

from django.db import migrations


def backfill_durum_and_cihaz_zamani(apps, schema_editor):
    """
    tamamlandi=False → durum='ABANDONED'
    tamamlandi=True  → durum='COMPLETED' (zaten default, yine de set et)
    olusturulma_tarihi → cihaz_zamani (mevcut kayıtlarda kiosk saati burada)
    """
    OturumLogu = apps.get_model("analytics", "OturumLogu")
    # ABANDONED
    OturumLogu.objects.filter(tamamlandi=False, durum="COMPLETED").update(durum="ABANDONED")
    # cihaz_zamani backfill — olusturulma_tarihi tarihsel olarak kiosk zamanıydı
    OturumLogu.objects.filter(cihaz_zamani__isnull=True).update(
        cihaz_zamani=models_F("olusturulma_tarihi")
    )


def models_F(field):
    from django.db.models import F
    return F(field)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_kiosk_activity_durum_fields'),
    ]

    operations = [
        migrations.RunPython(
            backfill_durum_and_cihaz_zamani,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
