# Generated by Django 5.2.16 on 2026-07-31 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_backfill_oturum_durum'),
        ('pharmacies', '0009_kiosk_last_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskEvent',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, help_text='Kiosk tarafindan uretilen idempotency anahtari.', unique=True)),
                ('event_type', models.CharField(choices=[('CONNECTION_LOST', 'Baglanti Kesildi'), ('CONNECTION_RESTORED', 'Baglanti Yenilendi'), ('SYNC_FAILED', 'Senkronizasyon Hatasi'), ('PLAYBACK_ERROR', 'Oynatma Hatasi'), ('APP_RESTART', 'Uygulama Yeniden Basladi'), ('OUTBOX_PRESSURE', 'Outbox Doluluk Uyarisi'), ('GENERAL_ERROR', 'Genel Hata')], db_index=True, default='GENERAL_ERROR', max_length=32)),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyari'), ('ERROR', 'Hata'), ('CRITICAL', 'Kritik')], db_index=True, default='WARNING', max_length=16)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, help_text='Kiosk cihaz zamani.', null=True)),
                ('received_at', models.DateTimeField(blank=True, help_text='Sunucu zamani.', null=True)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_events', to='pharmacies.kiosk')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiosk Event',
                'verbose_name_plural': 'Kiosk Events',
                'db_table': 'kiosk_events',
                'ordering': ('-olusturulma_tarihi',),
                'indexes': [models.Index(fields=['kiosk', 'event_type', 'olusturulma_tarihi'], name='kiosk_event_kiosk_i_6d5022_idx'), models.Index(fields=['severity', 'olusturulma_tarihi'], name='kiosk_event_severit_9f9cb3_idx')],
            },
        ),
    ]
