# Generated by Django 5.2.16 on 2026-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_offline_qr_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oturumlogu',
            name='qr_kodu',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True),
        ),
    ]
