# Generated by Django 5.2 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_alter_oturumlogu_qr_kodu"),
        ("barkod_logo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="oturumlogu",
            name="barkod_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Fişte başarıyla basılan barkod logosu. Null = fallback e-ISA başlığı kullanıldı.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="oturumlar",
                to="barkod_logo.barkodlogo",
            ),
        ),
    ]
