# Generated by Django 5.2.13 on 2026-05-03 22:10

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reklam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('ad', models.CharField(max_length=255)),
                ('medya_url', models.URLField(validators=[apps.campaigns.models._https_url_validator])),
                ('baslangic_tarihi', models.DateTimeField()),
                ('bitis_tarihi', models.DateTimeField()),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
                'db_table': 'reklamlar',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
    ]
