# Generated by Django 5.2.13 on 2026-05-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('media_url', models.URLField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('target_cities', models.JSONField(blank=True, default=list)),
                ('target_districts', models.JSONField(blank=True, default=list)),
                ('target_age_ranges', models.JSONField(blank=True, default=list)),
                ('target_genders', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
    ]
