# Generated by Django 5.2.13 on 2026-05-02 00:27

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='media_url',
            field=models.URLField(validators=[apps.campaigns.models.validate_https_url]),
        ),
    ]
