# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('lookups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reklam',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reklam',
            name='hedef_cinsiyetler',
            field=models.ManyToManyField(blank=True, related_name='reklamlar', to='lookups.cinsiyet'),
        ),
        migrations.AddField(
            model_name='reklam',
            name='hedef_ilceler',
            field=models.ManyToManyField(blank=True, related_name='reklamlar', to='lookups.ilce'),
        ),
        migrations.AddField(
            model_name='reklam',
            name='hedef_iller',
            field=models.ManyToManyField(blank=True, related_name='reklamlar', to='lookups.il'),
        ),
        migrations.AddField(
            model_name='reklam',
            name='hedef_yas_araliklari',
            field=models.ManyToManyField(blank=True, related_name='reklamlar', to='lookups.yasaraligi'),
        ),
        migrations.AddField(
            model_name='reklam',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
