# Generated by Copilot on 2026-05-09

import apps.campaigns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_reklam_ek_alanlar"),
        ("pharmacies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reklam",
            name="medya_url",
            field=models.URLField(
                max_length=2048,
                validators=[apps.campaigns.models._https_url_validator],
            ),
        ),
        migrations.CreateModel(
            name="ReklamTakvim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("guncellenme_tarihi", models.DateTimeField(auto_now_add=True)),
                ("surum", models.PositiveIntegerField(default=1, editable=False)),
                ("baslangic_saat", models.PositiveSmallIntegerField()),
                ("bitis_saat", models.PositiveSmallIntegerField()),
                ("aktif", models.BooleanField(default=True)),
                (
                    "guncelleyen",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reklam_takvimi",
                        to="pharmacies.kiosk",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reklam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takvim_atamalari",
                        to="campaigns.reklam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reklam Takvim Ataması",
                "verbose_name_plural": "Reklam Takvim Atamaları",
                "db_table": "reklam_takvimi",
                "ordering": ("kiosk_id", "baslangic_saat", "bitis_saat"),
            },
        ),
        migrations.AddConstraint(
            model_name="reklamtakvim",
            constraint=models.CheckConstraint(
                condition=models.Q(baslangic_saat__gte=0)
                & models.Q(baslangic_saat__lte=23)
                & models.Q(bitis_saat__gte=1)
                & models.Q(bitis_saat__lte=24)
                & models.Q(baslangic_saat__lt=models.F("bitis_saat")),
                name="reklam_takvimi_saat_araligi_gecerli",
            ),
        ),
    ]
