# Generated by Django 5.2.13 on 2026-05-09 21:21

import apps.campaigns.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_reklam_takvimi'),
        ('pharmacies', '0004_kiosk_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advertiser_id', models.UUIDField(help_text="Reklamveren (advertiser) UUID'si — harici sistem kimligi.")),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=16)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_pharmacies', models.ManyToManyField(blank=True, help_text='Bos liste = tum eczanelere yayinla.', related_name='dooh_campaigns', to='pharmacies.eczane')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'dooh_campaigns',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_url', models.URLField(max_length=2048, validators=[apps.campaigns.models._https_url_validator])),
                ('duration_seconds', models.PositiveSmallIntegerField(help_text='Yayin suresi (saniye). Tipik: 5, 10, 15, 30.')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('checksum', models.CharField(blank=True, default='', help_text='Edge tarafi cache invalidation icin.', max_length=128)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='campaigns.campaign')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creative',
                'verbose_name_plural': 'Creatives',
                'db_table': 'dooh_creatives',
                'ordering': ('campaign_id', 'olusturulma_tarihi'),
            },
        ),
        migrations.CreateModel(
            name='HouseAd',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('media_url', models.URLField(max_length=2048, validators=[apps.campaigns.models._https_url_validator])),
                ('duration_seconds', models.PositiveSmallIntegerField(default=10)),
                ('aktif', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Dusuk degerli once secilir (filler queue ordering).')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'House Ad',
                'verbose_name_plural': 'House Ads',
                'db_table': 'dooh_house_ads',
                'ordering': ('priority', 'olusturulma_tarihi'),
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('target_hour', models.PositiveSmallIntegerField()),
                ('loop_duration_seconds', models.PositiveSmallIntegerField(default=60)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='pharmacies.kiosk')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'db_table': 'dooh_playlists',
                'ordering': ('kiosk_id', 'target_date', 'target_hour'),
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playback_order', models.PositiveSmallIntegerField()),
                ('estimated_start_offset_seconds', models.PositiveSmallIntegerField()),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='campaigns.creative')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house_ad', models.ForeignKey(blank=True, help_text='Filler (Pass 4) icin; creative NULL olur.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='campaigns.housead')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.playlist')),
            ],
            options={
                'verbose_name': 'Playlist Item',
                'verbose_name_plural': 'Playlist Items',
                'db_table': 'dooh_playlist_items',
                'ordering': ('playlist_id', 'playback_order'),
            },
        ),
        migrations.CreateModel(
            name='PlayLog',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(db_index=True)),
                ('duration_played', models.PositiveSmallIntegerField(help_text='Gercekten oynatilan sure (saniye).')),
                ('creative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_logs', to='campaigns.creative')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('house_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_logs', to='campaigns.housead')),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_logs', to='pharmacies.kiosk')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Play Log',
                'verbose_name_plural': 'Play Logs',
                'db_table': 'dooh_play_logs',
                'ordering': ('-played_at',),
            },
        ),
        migrations.CreateModel(
            name='PricingMatrix',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price_per_second', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('prime_time_coefficient', models.DecimalField(decimal_places=3, default=1.5, max_digits=6)),
                ('prime_hours', models.JSONField(default=list, help_text='Prime time saatleri, orn. [17,18,19,20].')),
                ('frequency_multipliers', models.JSONField(default=dict, help_text='Frekans tipine gore carpanlar, orn. {"PER_LOOP": 3.0, "PER_HOUR": 1.5, "PER_DAY": 1.0}.')),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('is_default', models.BooleanField(default=True)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pricing Matrix',
                'verbose_name_plural': 'Pricing Matrices',
                'db_table': 'dooh_pricing_matrix',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleRule',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency_type', models.CharField(choices=[('PER_LOOP', 'Per 60s loop'), ('PER_HOUR', 'Per hour'), ('PER_DAY', 'Per day')], max_length=16)),
                ('frequency_value', models.PositiveSmallIntegerField()),
                ('target_hours', models.JSONField(blank=True, help_text='Hedef saatler (0-23). Null/bos = tum gun.', null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rules', to='campaigns.campaign')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule Rule',
                'verbose_name_plural': 'Schedule Rules',
                'db_table': 'dooh_schedule_rules',
                'ordering': ('campaign_id', 'frequency_type'),
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='dooh_campai_status_799ea1_idx'),
        ),
        migrations.AddConstraint(
            model_name='creative',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 1), ('duration_seconds__lte', 60)), name='dooh_creative_duration_1_60'),
        ),
        migrations.AddConstraint(
            model_name='housead',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gte', 1), ('duration_seconds__lte', 60)), name='dooh_house_ad_duration_1_60'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('kiosk', 'target_date', 'target_hour'), name='dooh_playlist_kiosk_date_hour_uniq'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(condition=models.Q(('target_hour__gte', 0), ('target_hour__lte', 23)), name='dooh_playlist_hour_0_23'),
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'playback_order'], name='dooh_playli_playlis_abcb93_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['kiosk', 'played_at'], name='dooh_play_l_kiosk_i_2d1d35_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['creative', 'played_at'], name='dooh_play_l_creativ_0c3553_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulerule',
            constraint=models.CheckConstraint(condition=models.Q(('frequency_value__gte', 1)), name='dooh_rule_freq_value_min_1'),
        ),
    ]
