# Generated by Django 5.2.13 on 2026-05-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_delete_reklamgosterim'),
        ('campaigns', '0006_campaign_creative_housead_playlist_playlistitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reklamtakvim',
            name='reklam',
        ),
        migrations.RemoveField(
            model_name='reklamtakvim',
            name='guncelleyen',
        ),
        migrations.RemoveField(
            model_name='reklamtakvim',
            name='kiosk',
        ),
        migrations.RemoveField(
            model_name='reklamtakvim',
            name='olusturan',
        ),
        migrations.DeleteModel(
            name='Reklam',
        ),
        migrations.DeleteModel(
            name='ReklamTakvim',
        ),
    ]
