# Generated by Django 5.2.13 on 2026-05-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_reklamtakvim_reklam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='advertiser_name',
            field=models.CharField(blank=True, default='', help_text='Reklamveren adi (admin panel icin serbest metin).', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='advertiser_id',
            field=models.UUIDField(blank=True, help_text="Reklamveren (advertiser) UUID'si — harici sistem kimligi (opsiyonel).", null=True),
        ),
    ]
