# Generated by Django 5.2.13 on 2026-05-09 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_advertiser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerule',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rule', to='campaigns.campaign'),
        ),
    ]
