# Generated by Django 5.2.13 on 2026-05-10 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_schedulerule_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistitem',
            name='creative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='campaigns.creative'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='house_ad',
            field=models.ForeignKey(blank=True, help_text='Filler (Pass 4) icin; creative NULL olur.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='campaigns.housead'),
        ),
    ]
