# Generated by Django 5.2.13 on 2026-05-10 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_fix_playlistitem_cascade'),
        ('lookups', '0001_initial'),
        ('pharmacies', '0004_kiosk_ad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='frequency_cap_per_hour',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Saatte maksimum gösterim sayısı (opsiyonel). Örn: saatte en fazla 2 kez çıksın.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='impression_goal',
            field=models.PositiveIntegerField(blank=True, help_text='Toplam gösterim hedefi (opsiyonel). Örn: 5000 kez göster.', null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Her üretimde artan versiyon numarası. Kiosk ping ile karşılaştırır.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_pharmacies',
            field=models.ManyToManyField(blank=True, help_text='[Eski] Bos liste = tum eczanelere yayinla. Yeni kampanyalar CampaignTarget kullanir.', related_name='dooh_campaigns', to='pharmacies.eczane'),
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('IL', 'İl (Tüm ilçe ve eczaneler)'), ('ILCE', 'İlçe (Tüm eczaneler)'), ('ECZANE', 'Spesifik Eczane')], max_length=8)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='campaigns.campaign')),
                ('eczane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pharmacies.eczane')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('il', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.il')),
                ('ilce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lookups.ilce')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Target',
                'verbose_name_plural': 'Campaign Targets',
                'db_table': 'dooh_campaign_targets',
                'ordering': ('campaign_id', 'target_type'),
            },
        ),
    ]
