# Generated by Django 5.2.13 on 2026-05-19 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_target_pacing_version'),
        ('pharmacies', '0005_kiosk_is_online_kiosk_last_playlist_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_guaranteed',
            field=models.BooleanField(default=False, help_text="True ise kapasite dolsa bile hiç atlanmaz; Pass 4 filler'dan yer açılır."),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='Slot çakışmasında öncelik (1=en yüksek, 100=en düşük). Düşük değer önce yerleşir.'),
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('RUNNING', 'Çalışıyor'), ('DONE', 'Tamamlandı'), ('FAILED', 'Başarısız')], db_index=True, default='PENDING', max_length=10)),
                ('total_kiosks', models.PositiveIntegerField(default=0)),
                ('done_kiosks', models.PositiveIntegerField(default=0)),
                ('failed_kiosks', models.PositiveIntegerField(default=0)),
                ('playlists_generated', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(default='manual', help_text="'manual' | 'nightly' | 'campaign_change'", max_length=64)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kiosk', models.ForeignKey(blank=True, help_text='NULL ise tüm aktif kiosklar için üretim yapılır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='pharmacies.kiosk')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation Job',
                'verbose_name_plural': 'Generation Jobs',
                'db_table': 'dooh_generation_jobs',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='PlaylistTemplate',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('loop_duration_seconds', models.PositiveSmallIntegerField(default=60)),
                ('slots', models.JSONField(default=list, help_text='[{campaign_id, creative_id, offset_seconds, duration_seconds}, ...] seklinde 60sn slot listesi.')),
                ('description', models.TextField(blank=True, default='')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist Template',
                'verbose_name_plural': 'Playlist Templates',
                'db_table': 'dooh_playlist_templates',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
    ]
