# Generated by Django 5.2.13 on 2026-05-20 00:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_playlisttemplate_target_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slots', models.JSONField(default=list, help_text='[{hour: 0..23, hour_plan_id: uuid}, ...] seklinde 24 saatlik HourPlan atamalari.')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day Plan',
                'verbose_name_plural': 'Day Plans',
                'db_table': 'dooh_day_plans',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='HourPlan',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slots', models.JSONField(default=list, help_text='[{offset_minutes, duration_minutes, loop_template_id}, ...] seklinde 60 dakikalik slot listesi.')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hour Plan',
                'verbose_name_plural': 'Hour Plans',
                'db_table': 'dooh_hour_plans',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
    ]
