# Generated by Django 5.2.16 on 2026-07-21 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_creative_object_key_housead_object_key'),
        ('pharmacies', '0007_kiosk_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTotalAllocation',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_target', models.PositiveIntegerField(help_text='DeliveryRule.count (kampanya toplami).')),
                ('allocated_total', models.PositiveIntegerField(default=0, help_text='Kiosk-gun kotalarinin toplami.')),
            ],
            options={
                'verbose_name': 'Campaign Total Allocation',
                'verbose_name_plural': 'Campaign Total Allocations',
                'db_table': 'dooh_campaign_total_allocations',
                'ordering': ('planning_run_id', 'campaign_id'),
            },
        ),
        migrations.CreateModel(
            name='DeliveryRule',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_type', models.CharField(choices=[('TIME_WINDOW', 'Belirli Zaman Penceresi'), ('PER_HOUR', 'Saatte N kez (per-kiosk)'), ('PER_DAY', 'Gunde N kez (per-kiosk)'), ('CAMPAIGN_TOTAL', 'Kampanya Toplami (global)'), ('LEGACY_PER_LOOP', 'Loop Basi (Legacy, salt-okunur)')], max_length=20)),
                ('count', models.PositiveIntegerField(help_text='Gosterim sayisi (TIME_WINDOW/PER_HOUR/PER_DAY/CAMPAIGN_TOTAL icin).')),
                ('window_start_time', models.TimeField(blank=True, help_text='TIME_WINDOW baslangici (HH:MM). TIME_WINDOW icin zorunlu.', null=True)),
                ('window_end_time', models.TimeField(blank=True, help_text='TIME_WINDOW bitisi (HH:MM). TIME_WINDOW icin zorunlu.', null=True)),
                ('active_hours', models.JSONField(blank=True, help_text='Aktif saatler (0-23). Null = tum gun.', null=True)),
                ('active_weekdays', models.JSONField(blank=True, help_text='Aktif haftanin gunleri (0=Pzt..6=Paz). Null = her gun.', null=True)),
                ('guarantee_mode', models.CharField(choices=[('GUARANTEED', 'Garanti (kapasite ayrilir)'), ('BEST_EFFORT', 'En Iyi Caba (bos slota yerlesir)')], default='BEST_EFFORT', max_length=12)),
                ('max_per_hour', models.PositiveSmallIntegerField(blank=True, help_text='Saatlik azami gosterim (opsiyonel cap, per-kiosk).', null=True)),
            ],
            options={
                'verbose_name': 'Delivery Rule',
                'verbose_name_plural': 'Delivery Rules',
                'db_table': 'dooh_delivery_rules',
                'ordering': ('campaign_id',),
            },
        ),
        migrations.CreateModel(
            name='KioskDayQuota',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quota', models.PositiveIntegerField(default=0, help_text='Bu kiosk-gun icin izin verilen gosterim sayisi.')),
                ('placed', models.PositiveIntegerField(default=0, help_text='Uretimde gercekten yerlestirilen gosterim sayisi.')),
            ],
            options={
                'verbose_name': 'Kiosk Day Quota',
                'verbose_name_plural': 'Kiosk Day Quotas',
                'db_table': 'dooh_kiosk_day_quotas',
                'ordering': ('planning_run_id', 'campaign_id', 'date'),
            },
        ),
        migrations.CreateModel(
            name='KioskDesiredBundle',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desired_bundle_version', models.PositiveIntegerField(default=0, help_text='Kiosk bazinda monoton artan versiyon (Max(Playlist.version) KULLANILMAZ).')),
                ('content_fingerprint', models.CharField(blank=True, default='', help_text='SHA-256 (hex) canonical payload hash. Degismemisse version artmaz.', max_length=64)),
                ('valid_from', models.DateField(blank=True, help_text='Gecerli horizon baslangici.', null=True)),
                ('horizon_days', models.PositiveSmallIntegerField(default=3, help_text='Kac gun ileri playlist uretiliyor (rolling horizon).')),
            ],
            options={
                'verbose_name': 'Kiosk Desired Bundle',
                'verbose_name_plural': 'Kiosk Desired Bundles',
                'db_table': 'dooh_kiosk_desired_bundles',
                'ordering': ('kiosk_id',),
            },
        ),
        migrations.CreateModel(
            name='PlanningRun',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizon_start', models.DateField()),
                ('horizon_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('ACTIVE', 'Aktif'), ('DONE', 'Tamamlandi'), ('FAILED', 'Basarisiz')], default='PENDING', max_length=8)),
            ],
            options={
                'verbose_name': 'Planning Run',
                'verbose_name_plural': 'Planning Runs',
                'db_table': 'dooh_planning_runs',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='follows',
            field=models.ForeignKey(blank=True, help_text='A->B ardisillik: bu kampanya hangi kampanyadan hemen sonra oynansin. Yalniz ikili (A->B); zincir/dongü yasak. Service-level validation uygulanir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_by', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_scope',
            field=models.CharField(blank=True, choices=[('ALL', 'Tum aktif kiosklar'), ('RULES', 'Hedefleme kurallari')], help_text="Hedefleme kapsami. NULL = legacy davranis (CampaignTarget yoksa tum kiosklar). ALL = tum aktif kiosklar dinamik. RULES = CampaignTarget kayitlarina gore (include/exclude). Faz 1'de eklendu; Faz 2+'de zorunlu olmasi planlanmaktadir.", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='kiosk',
            field=models.ForeignKey(blank=True, help_text='KIOSK tipi icin zorunlu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pharmacies.kiosk'),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='mode',
            field=models.CharField(blank=True, choices=[('INCLUDE', 'Dahil et'), ('EXCLUDE', 'Haric tut')], help_text='INCLUDE (dahil et) veya EXCLUDE (hariç tut). NULL = legacy INCLUDE davranisi.', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='creative',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, help_text='Rotasyon agirligi (1=esit). V2 motor agirlikli round-robin icin kullanir.'),
        ),
        migrations.AddField(
            model_name='playlog',
            name='play_event_id',
            field=models.UUIDField(blank=True, db_index=True, help_text="Kiosk tarafindan uretilen idempotency anahtari (Faz 5'te unique constraint eklenir). K5: nullable ekle -> backfill -> dogru la -> unique/not-null.", null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='frequency_cap_per_hour',
            field=models.PositiveSmallIntegerField(blank=True, help_text='[Eski] Saatlik azami gosterim. Yeni: DeliveryRule.max_per_hour.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='impression_goal',
            field=models.PositiveIntegerField(blank=True, help_text='[Eski] Toplam gosterim hedefi. Yeni: DeliveryRule(CAMPAIGN_TOTAL).', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_guaranteed',
            field=models.BooleanField(default=False, help_text='[Eski] True ise hic atlanmaz. Yeni: DeliveryRule.guarantee_mode=GUARANTEED.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='priority',
            field=models.PositiveSmallIntegerField(default=50, help_text='Slot cakismasinda oncelik (1=en yuksek, 100=en dusuk). Dusuk deger once yerlesir.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Iptal')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='campaigntarget',
            name='target_type',
            field=models.CharField(choices=[('IL', 'İl (Tüm ilçe ve eczaneler)'), ('ILCE', 'İlçe (Tüm eczaneler)'), ('ECZANE', 'Spesifik Eczane'), ('KIOSK', 'Tekil Kiosk')], max_length=8),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('follows', models.F('id')), _negated=True), name='dooh_campaign_no_self_follow'),
        ),
        migrations.AddField(
            model_name='campaigntotalallocation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_allocations', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigntotalallocation',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntotalallocation',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrule',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rule', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='deliveryrule',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrule',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kioskdayquota',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_quotas', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='kioskdayquota',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kioskdayquota',
            name='kiosk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pharmacies.kiosk'),
        ),
        migrations.AddField(
            model_name='kioskdayquota',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kioskdesiredbundle',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kioskdesiredbundle',
            name='kiosk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desired_bundle', to='pharmacies.kiosk'),
        ),
        migrations.AddField(
            model_name='kioskdesiredbundle',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningrun',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planningrun',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kioskdayquota',
            name='planning_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_quotas', to='campaigns.planningrun'),
        ),
        migrations.AddField(
            model_name='campaigntotalallocation',
            name='planning_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='campaigns.planningrun'),
        ),
        migrations.AddConstraint(
            model_name='deliveryrule',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='dooh_delivery_rule_count_min_1'),
        ),
        migrations.AddConstraint(
            model_name='kioskdayquota',
            constraint=models.UniqueConstraint(fields=('planning_run', 'campaign', 'kiosk', 'date'), name='dooh_kdq_run_campaign_kiosk_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='campaigntotalallocation',
            constraint=models.UniqueConstraint(fields=('planning_run', 'campaign'), name='dooh_cta_run_campaign_uniq'),
        ),
    ]
