# Generated by Django 5.2.16 on 2026-07-21 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_faz1_additive_schema'),
        ('pharmacies', '0007_kiosk_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kioskdayquota',
            constraint=models.CheckConstraint(condition=models.Q(('quota__gte', 0)), name='dooh_kdq_quota_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='kioskdayquota',
            constraint=models.CheckConstraint(condition=models.Q(('placed__gte', 0)), name='dooh_kdq_placed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='kioskdayquota',
            constraint=models.CheckConstraint(condition=models.Q(('placed__lte', models.F('quota'))), name='dooh_kdq_placed_lte_quota'),
        ),
    ]
