# Generated by Django 5.2.16 on 2026-07-22 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_faz1_kiosk_quota_constraints'),
        ('pharmacies', '0007_kiosk_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(condition=models.Q(('follows__isnull', False)), fields=('follows',), name='dooh_campaign_follows_unique_predecessor'),
        ),
    ]
