# Generated by Django 5.2.16 on 2026-07-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_faz1_campaign_follows_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Toplam çalıştırma denemesi.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='available_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Retry gecikmesi sonrası bu zamandan itibaren çalıştırılabilir.', null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, help_text="Coalescing anahtarı. Format: 'kd:{kiosk_id}:{date}'. Aynı anahtar için PENDING job varken yeni oluşturulmaz.", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Worker lease süresi. Bu aşılırsa RUNNING → RETRY (stale recovery).', null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maksimum deneme sayısı (aşılırsa FAILED).'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='İş yükü: {kiosk_id, date, trigger_reason, ...}. Model instance, credential veya secret içermez.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='worker_id',
            field=models.CharField(blank=True, help_text='İşi sahiplenen worker kimliği (lease için). RUNNING durumunda dolu.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Bekliyor'), ('RUNNING', 'Çalışıyor'), ('DONE', 'Tamamlandı'), ('FAILED', 'Başarısız'), ('RETRY', 'Yeniden Deneniyor')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
