# Generated by Django 5.2.16 on 2026-07-31 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_pharmacycampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacycampaign',
            options={'ordering': ('-olusturulma_tarihi',), 'verbose_name': 'Pharmacy Campaign', 'verbose_name_plural': 'Pharmacy Campaigns'},
        ),
        migrations.RenameIndex(
            model_name='pharmacycampaign',
            new_name='pharmacy_ca_is_acti_092100_idx',
            old_name='pharmacy_camp_active_date_idx',
        ),
    ]
