# Generated by Django 5.2.16 on 2026-07-31 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_pharmacycampaign_targeting'),
        ('pharmacies', '0009_kiosk_last_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlog',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='playlog',
            name='error_summary',
            field=models.CharField(blank=True, default='', help_text='FAILED durumunda sanitize edilmis kisa hata ozeti.', max_length=255),
        ),
        migrations.AddField(
            model_name='playlog',
            name='expected_duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Beklenen oynatma suresi (saniye). PlaylistItem.duration_seconds'tan gelir.", null=True),
        ),
        migrations.AddField(
            model_name='playlog',
            name='occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Kiosk cihaz zamani.', null=True),
        ),
        migrations.AddField(
            model_name='playlog',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='Sunucu zamani (ingest aninda set edilir).', null=True),
        ),
        migrations.AddField(
            model_name='playlog',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Basladi'), ('COMPLETED', 'Tamamlandi'), ('FAILED', 'Basarisiz'), ('INTERRUPTED', 'Kesildi')], db_index=True, default='COMPLETED', help_text='Oynatma durumu. Eski kayitlar COMPLETED varsayilir.', max_length=16),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='play_event_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Kiosk tarafindan uretilen idempotency anahtari. NULL = eski kiosk surumu.', null=True),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['status', 'played_at'], name='dooh_play_l_status_fc91f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlog',
            constraint=models.UniqueConstraint(condition=models.Q(('play_event_id__isnull', False)), fields=('play_event_id',), name='dooh_play_log_play_event_id_unique_non_null'),
        ),
    ]
