# Generated by Django 5.2.16 on 2026-08-16 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _delete_house_ad_filler_items(apps, schema_editor):
    """HouseAd kaldiriliyor: yalniz house_ad dolgusu olan (creative NULL) playlist
    item'lari sil. Campaign creative item'larina dokunulmaz; campaign/creative ve
    proof-of-play kayitlari korunur."""
    PlaylistItem = apps.get_model("campaigns", "PlaylistItem")
    PlaylistItem.objects.filter(creative__isnull=True).delete()


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0026_creative_active_object_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_delete_house_ad_filler_items, _noop_reverse),
        migrations.RemoveField(
            model_name='playlistitem',
            name='house_ad',
        ),
        migrations.RemoveField(
            model_name='playlog',
            name='house_ad',
        ),
        migrations.CreateModel(
            name='IdleScreenContent',
            fields=[
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(help_text='Idle ekrani basligi (duz metin, en fazla 250 karakter).', max_length=250)),
                ('metin', models.CharField(help_text='Idle ekrani metni (duz metin, en fazla 500 karakter).', max_length=1000)),
                ('aktif', models.BooleanField(default=True, help_text='Pasif icerikler kiosk katalogda gorunmez.')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idle Screen Content',
                'verbose_name_plural': 'Idle Screen Contents',
                'db_table': 'dooh_idle_screen_contents',
                'ordering': ('-guncellenme_tarihi',),
            },
        ),
        migrations.DeleteModel(
            name='HouseAd',
        ),
    ]
