# Generated by Django 5.2.16 on 2026-08-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_remove_playlistitem_house_ad_remove_playlog_house_ad_and_more'),
        ('products', '0012_add_danisma_sira'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlescreencontent',
            name='kategori',
            field=models.ForeignKey(blank=True, help_text='Opsiyonel: bu icerigi iliskilendiren saglik kategorisi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idle_contents', to='products.kategori'),
        ),
    ]
