# Generated by Django 5.2.16 on 2026-09-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0030_make_idle_metin_en_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlescreencontent',
            name='baslik_en',
            field=models.CharField(blank=True, default='', help_text='Ingilizce idle basligi. Bos = kioskta Turkce basliga geri doner.', max_length=250, null=True),
        ),
    ]
