# Generated by Django 5.2.13 on 2026-05-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DenetimLogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktor_ozeti', models.CharField(blank=True, default='', max_length=255)),
                ('eylem', models.CharField(choices=[('create', 'Olustur'), ('update', 'Guncelle'), ('delete', 'Sil'), ('login', 'Giris'), ('login_failed', 'Giris Basarisiz'), ('kiosk_online', 'Kiosk Online'), ('kiosk_offline', 'Kiosk Offline'), ('kiosk_heartbeat', 'Kiosk Heartbeat'), ('regenerate_key', 'App-Key Yenile'), ('other', 'Diger')], max_length=32)),
                ('hedef_tipi', models.CharField(blank=True, default='', max_length=64)),
                ('hedef_id', models.CharField(blank=True, default='', max_length=64)),
                ('ozet', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('kiosk_mac', models.CharField(blank=True, default='', max_length=17)),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Denetim Logu',
                'verbose_name_plural': 'Denetim Loglari',
                'db_table': 'denetim_loglari',
                'ordering': ('-olusturulma_tarihi',),
            },
        ),
    ]
