# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denetimlogu',
            name='aktor',
            field=models.ForeignKey(blank=True, help_text='Islemi yapan kullanici. Kiosk olaylari icin NULL olabilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denetim_loglari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='denetimlogu',
            index=models.Index(fields=['eylem', 'olusturulma_tarihi'], name='denetim_log_eylem_84a254_idx'),
        ),
        migrations.AddIndex(
            model_name='denetimlogu',
            index=models.Index(fields=['hedef_tipi', 'hedef_id'], name='denetim_log_hedef_t_51eb16_idx'),
        ),
        migrations.AddIndex(
            model_name='denetimlogu',
            index=models.Index(fields=['kiosk_mac', 'olusturulma_tarihi'], name='denetim_log_kiosk_m_2e59bb_idx'),
        ),
    ]
