# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinsiyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=4, unique=True)),
                ('ad', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Cinsiyet',
                'verbose_name_plural': 'Cinsiyetler',
                'db_table': 'cinsiyetler',
                'ordering': ('ad',),
            },
        ),
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=64, unique=True)),
                ('plaka', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Il',
                'verbose_name_plural': 'Iller',
                'db_table': 'iller',
                'ordering': ('ad',),
            },
        ),
        migrations.CreateModel(
            name='YasAraligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=8, unique=True)),
                ('ad', models.CharField(max_length=32)),
                ('alt_sinir', models.PositiveSmallIntegerField()),
                ('ust_sinir', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Yas Araligi',
                'verbose_name_plural': 'Yas Araliklari',
                'db_table': 'yas_araliklari',
                'ordering': ('alt_sinir',),
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=64)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilceler', to='lookups.il')),
            ],
            options={
                'verbose_name': 'Ilce',
                'verbose_name_plural': 'Ilceler',
                'db_table': 'ilceler',
                'ordering': ('il__ad', 'ad'),
                'unique_together': {('il', 'ad')},
            },
        ),
    ]
