# Generated by Django 5.2.13 on 2026-05-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eczane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('ad', models.CharField(max_length=255)),
                ('adres', models.TextField(blank=True, default='')),
                ('sahip_adi', models.CharField(blank=True, default='', max_length=128)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Eczane',
                'verbose_name_plural': 'Eczaneler',
                'db_table': 'eczaneler',
                'ordering': ('ad',),
            },
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('mac_adresi', models.CharField(max_length=17, unique=True)),
                ('uygulama_anahtari', models.CharField(max_length=128, unique=True)),
                ('aktif', models.BooleanField(default=True)),
                ('son_goruldu', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kiosk',
                'verbose_name_plural': 'Kiosklar',
                'db_table': 'kiosklar',
                'ordering': ('id',),
            },
        ),
    ]
