# Generated by Django 5.2.13 on 2026-05-03 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eczane',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eczane',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eczaneler', to='lookups.il'),
        ),
        migrations.AddField(
            model_name='eczane',
            name='ilce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eczaneler', to='lookups.ilce'),
        ),
        migrations.AddField(
            model_name='eczane',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='eczane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosklar', to='pharmacies.eczane'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='guncelleyen',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='olusturan',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
