# Generated by Django 5.2.13 on 2026-05-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_kiosk_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='last_playlist_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
