# Generated by Django 5.2.16 on 2026-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0007_kiosk_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='applied_horizon_end',
            field=models.DateField(blank=True, help_text="Kiosk'un SQLite'a uyguladığı horizon aralığı bitişi.", null=True),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='applied_horizon_start',
            field=models.DateField(blank=True, help_text="Kiosk'un SQLite'a uyguladığı horizon aralığı başlangıcı.", null=True),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='applied_playlist_version',
            field=models.PositiveIntegerField(blank=True, help_text='Kiosk ACK ile raporlanan son başarıyla uygulanan playlist versiyonu.', null=True),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='last_v2_fingerprints',
            field=models.JSONField(blank=True, default=dict, help_text="Tarih→fingerprint map. Son başarılı V2 publish'in canonical içerik özeti."),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='playlist_applied_at',
            field=models.DateTimeField(blank=True, help_text="Son ACK'in server'a geldiği zaman (server clock).", null=True),
        ),
    ]
