# Generated by Django 5.2.16 on 2026-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0017_kiosk_idle_audio_countdown_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='eczane',
            name='vergi_no',
            field=models.CharField(blank=True, default='', help_text='Vergi dairesi / vergi numarası (sözleşmede görünür).', max_length=20),
        ),
    ]
