# Generated by Django 5.2.16 on 2026-09-30 23:19

from django.db import migrations, models


NEW_SYSTEM_ANNOUNCEMENTS = (
    (
        "PAYMENT_DUE_SOON",
        "Ödeme Gününüz Yaklaşıyor",
        "Fatura ödemenizin son gününe az kaldı. Lütfen ödemenizi tamamlayın; "
        "aksi halde hesabınız kısıtlanacaktır.",
        "Ödeme Yap",
    ),
    (
        "CONTRACT_EXPIRING",
        "Sözleşmeniz Bitmek Üzere",
        "Sözleşmenizin bitişine 7 günden az kaldı. Kesintisiz hizmet için "
        "sözleşmenizi uzatın veya yenileyin.",
        "Hesabım ve Ödemeler",
    ),
)


def seed_new_system_announcements(apps, schema_editor):
    Announcement = apps.get_model("announcements", "Announcement")
    for system_key, title, message, action_label in NEW_SYSTEM_ANNOUNCEMENTS:
        Announcement.objects.get_or_create(
            system_key=system_key,
            defaults={
                "kind": "SYSTEM",
                "title": title,
                "message": message,
                "action_label": action_label,
                "severity": "ACTION_REQUIRED",
                "active": True,
                "recurrence": "ONCE",
                "target_scope": "ALL",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_duty_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='system_key',
            field=models.CharField(blank=True, choices=[('DUTY_NEXT_MONTH_MISSING', 'Gelecek ay nöbet bilgisi eksik'), ('DUTY_CURRENT_MONTH_MISSING', 'Bu ay nöbet bilgisi eksik'), ('PAYMENT_DUE_SOON', 'Ödeme gününe az kaldı'), ('CONTRACT_EXPIRING', 'Sözleşme bitişine az kaldı')], editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.RunPython(seed_new_system_announcements, migrations.RunPython.noop),
    ]
