# Generated by Django 5.2.16 on 2026-08-15 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0010_kiosk_eczane_kiosk_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalepSayac',
            fields=[
                ('yil', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('son_sayi', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'destek_talep_sayac',
            },
        ),
        migrations.CreateModel(
            name='DestekParametresi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('grup', models.CharField(choices=[('TALEP_TURU', 'Talep Türü'), ('ALAN', 'Alan'), ('ALT_KONU', 'Alt Konu'), ('DURUM', 'Durum')], db_index=True, max_length=20)),
                ('kod', models.CharField(max_length=50, unique=True)),
                ('ad', models.CharField(max_length=100)),
                ('sira', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('aktif', models.BooleanField(db_index=True, default=True)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ust_parametre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_parametreler', to='destek.destekparametresi')),
            ],
            options={
                'verbose_name': 'Destek Parametresi',
                'verbose_name_plural': 'Destek Parametreleri',
                'db_table': 'destek_parametreler',
                'ordering': ('grup', 'sira', 'ad'),
            },
        ),
        migrations.CreateModel(
            name='DestekTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('talep_no', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('aciklama', models.TextField(max_length=1000)),
                ('son_hareket_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alan', models.ForeignKey(help_text='Grup: ALAN', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='destek.destekparametresi')),
                ('alt_konu', models.ForeignKey(help_text='Grup: ALT_KONU', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='destek.destekparametresi')),
                ('durum', models.ForeignKey(help_text='Grup: DURUM', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='destek.destekparametresi')),
                ('eczane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destek_talepleri', to='pharmacies.eczane')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kiosk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destek_talepleri', to='pharmacies.kiosk')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan_kullanici', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acilan_destek_talepleri', to=settings.AUTH_USER_MODEL)),
                ('talep_turu', models.ForeignKey(help_text='Grup: TALEP_TURU', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='destek.destekparametresi')),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'db_table': 'destek_talepler',
                'ordering': ('-son_hareket_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='DestekYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('yorum_metni', models.TextField(max_length=1000)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('talep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='destek.destektalebi')),
            ],
            options={
                'verbose_name': 'Destek Yorumu',
                'verbose_name_plural': 'Destek Yorumları',
                'db_table': 'destek_yorumlar',
                'ordering': ('olusturulma_tarihi',),
            },
        ),
    ]
