# Generated by Django 5.2.13 on 2026-05-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('metin', models.CharField(max_length=255)),
                ('agirlik', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'db_table': 'cevaplar',
                'ordering': ('soru_id', '-agirlik'),
            },
        ),
        migrations.CreateModel(
            name='EtkenMadde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('ad', models.CharField(max_length=128, unique=True)),
                ('aciklama', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Etken Madde',
                'verbose_name_plural': 'Etken Maddeler',
                'db_table': 'etken_maddeler',
                'ordering': ('ad',),
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('ad', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('ikon', models.CharField(default='fa-circle', max_length=64)),
                ('hassas', models.BooleanField(default=False, help_text='Sessiz triyaj akisi (Akis B) icin isaretle.')),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'kategoriler',
                'ordering': ('ad',),
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('seed_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('metin', models.TextField()),
                ('sira', models.PositiveSmallIntegerField(default=0)),
                ('eslesme_kurallari', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'db_table': 'sorular',
                'ordering': ('kategori__ad', 'sira'),
            },
        ),
    ]
