# Generated by Django 5.2.13 on 2026-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_soru_etken_madde_through'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkenmadde',
            name='ad',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='soru',
            name='sira',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='soru',
            unique_together={('kategori', 'sira')},
        ),
    ]
