# Generated by Django 5.2.13 on 2026-05-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_soru_kategori_sira_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkenmadde',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
    ]
