# Generated by Django 5.2.13 on 2026-05-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_etken_madde_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='bagli_kategori',
            field=models.ForeignKey(blank=True, help_text='Bu kategorinin bagli oldugu ust/ilgili kategori.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_kategoriler', to='products.kategori'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='danisma',
            field=models.BooleanField(default=False, help_text='Eczaciya danisma akisi: yas/cinsiyet/soru gerekmez, sadece kategori secilir.'),
        ),
    ]
