# Generated by Django 5.2.13 on 2026-05-19 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_bagli_kategori_danisma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='danisma',
        ),
        migrations.RemoveField(
            model_name='kategori',
            name='hassas',
        ),
        migrations.CreateModel(
            name='Danisma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('ad', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('ikon', models.CharField(default='fa-comments', max_length=64)),
                ('aktif', models.BooleanField(default=True)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ust_kategori', models.ForeignKey(blank=True, help_text='Ust danisma kategorisi. Bos = kok seviyesi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_kategoriler', to='products.danisma')),
            ],
            options={
                'verbose_name': 'Danisma Kategorisi',
                'verbose_name_plural': 'Danisma Kategorileri',
                'db_table': 'danisma_kategorileri',
                'ordering': ('ad',),
            },
        ),
    ]
