# Generated by Django 5.2.13 on 2026-05-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_hassas_danisma_bool_add_danisma_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soruetkenmadde',
            name='rol',
            field=models.CharField(choices=[('ana', 'Ana'), ('destekleyici', 'Destekleyici'), ('tamamlayici', 'Tamamlayici')], default='ana', max_length=16),
        ),
    ]
