# Generated by Django 5.2.16 on 2026-07-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_soruetkenmadde_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danisma',
            name='ad',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='ad',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
