# Generated by Django 5.2.16 on 2026-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_danisma_ad_alter_kategori_ad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danisma',
            options={'ordering': ('sira', 'ad'), 'verbose_name': 'Danisma Kategorisi', 'verbose_name_plural': 'Danisma Kategorileri'},
        ),
        migrations.AddField(
            model_name='danisma',
            name='sira',
            field=models.PositiveSmallIntegerField(default=100, help_text='Goruntuleme sirasi (kucuk deger once). Esit sirada ada gore sirala.'),
        ),
    ]
