# Generated by Django 5.2.16 on 2026-09-30 21:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0016_kiosk_build_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CihazOdemePlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('pesin_fiyat', models.DecimalField(decimal_places=2, help_text='Cihaz peşin fiyatı (TL).', max_digits=12)),
                ('vade_farki_orani', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peşin fiyat üzerine eklenecek vade farkı yüzdesi (%).', max_digits=6)),
                ('taksit_sayisi', models.PositiveSmallIntegerField(choices=[(4, '4 Taksit'), (8, '8 Taksit')], default=4)),
                ('baslangic_tarihi', models.DateField(help_text='İlk cihaz taksitinin faturalanacağı ay.')),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal')], db_index=True, default='AKTIF', max_length=16)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cihaz Ödeme Planı',
                'verbose_name_plural': 'Cihaz Ödeme Planları',
                'db_table': 'abonelik_cihaz_odeme_planlari',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('tip', models.CharField(choices=[('KULLANIM_BEDELI', 'Kullanım Bedeli'), ('CIHAZ_TAKSIT', 'Cihaz Taksiti')], db_index=True, max_length=20)),
                ('donem', models.CharField(db_index=True, help_text='Faturalama dönemi (YYYY-MM).', max_length=7)),
                ('taksit_no', models.PositiveSmallIntegerField(blank=True, help_text='Cihaz taksitleri için sıra numarası.', null=True)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vade_tarihi', models.DateField(db_index=True)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ODENDI', 'Ödendi'), ('GECIKTI', 'Gecikti'), ('IPTAL', 'İptal')], db_index=True, default='BEKLIYOR', max_length=16)),
                ('odenme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('aciklama', models.CharField(blank=True, default='', max_length=255)),
                ('cihaz_plani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturalar', to='abonelik.cihazodemeplani')),
                ('eczane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='pharmacies.eczane')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'db_table': 'abonelik_faturalar',
                'ordering': ('-vade_tarihi', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yontem', models.CharField(choices=[('KREDI_KARTI', 'Kredi Kartı'), ('OTOMATIK_CEKIM', 'Otomatik Çekim'), ('MANUEL', 'Manuel')], default='KREDI_KARTI', max_length=16)),
                ('odeme_tarihi', models.DateTimeField()),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='abonelik.fatura')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'db_table': 'abonelik_odemeler',
                'ordering': ('-odeme_tarihi', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Sozlesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('sozlesme_tipi_ay', models.PositiveSmallIntegerField(choices=[(12, '12 Ay'), (24, '24 Ay'), (36, '36 Ay')], default=24, help_text='Standart sözleşme süresi (ay).')),
                ('baslangic_tarihi', models.DateField(help_text='Sözleşme başlangıç tarihi.')),
                ('oteleme_ay', models.PositiveSmallIntegerField(default=0, help_text='Kullanım bedeli öteleme süresi (ay). Bu süre kadar fatura kesilmez ve süre sözleşme sonuna eklenir.')),
                ('aylik_kullanim_bedeli', models.DecimalField(decimal_places=2, default=Decimal('3900.00'), help_text='Aylık e-İSA kullanım bedeli (TL).', max_digits=12)),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('AKTIF', 'Aktif'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal')], db_index=True, default='TASLAK', max_length=16)),
                ('notlar', models.TextField(blank=True, default='')),
                ('eczane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sozlesmeler', to='pharmacies.eczane')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'db_table': 'abonelik_sozlesmeler',
                'ordering': ('-baslangic_tarihi', '-id'),
            },
        ),
        migrations.AddField(
            model_name='fatura',
            name='sozlesme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturalar', to='abonelik.sozlesme'),
        ),
        migrations.AddField(
            model_name='cihazodemeplani',
            name='sozlesme',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cihaz_plani', to='abonelik.sozlesme'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.UniqueConstraint(condition=models.Q(('taksit_no__isnull', False)), fields=('eczane', 'tip', 'donem', 'taksit_no'), name='uniq_fatura_eczane_tip_donem_taksit'),
        ),
        migrations.AddConstraint(
            model_name='fatura',
            constraint=models.UniqueConstraint(condition=models.Q(('taksit_no__isnull', True)), fields=('eczane', 'tip', 'donem'), name='uniq_fatura_eczane_tip_donem_notaksit'),
        ),
    ]
