# Generated by Django 5.2.16 on 2026-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='taksit_sayisi',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Taksit (Peşin)'), (4, '4 Taksit'), (8, '8 Taksit'), (12, '12 Taksit')], default=4),
        ),
    ]
