# Generated by Django 5.2.16 on 2026-09-30 22:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0002_alter_cihazodemeplani_taksit_sayisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='demo_gun',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Demo sözleşme süresi (gün, en fazla 30). Standart'ta boş.", null=True),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='ek_ay_toplam',
            field=models.PositiveSmallIntegerField(default=0, help_text='Uzatmalarla eklenen toplam ay (standart).'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='ek_gun_toplam',
            field=models.PositiveSmallIntegerField(default=0, help_text='Uzatmalarla eklenen toplam gün (demo).'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='onceki_sozlesme',
            field=models.ForeignKey(blank=True, help_text='Bu sözleşme bir öncekinin devamıysa (ör. demo→standart) bağlantı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sonraki_sozlesmeler', to='abonelik.sozlesme'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='tur',
            field=models.CharField(choices=[('DEMO', 'Demo'), ('STANDART', 'Standart')], db_index=True, default='STANDART', help_text='Sözleşme türü: demo (gün bazlı) veya standart (ay bazlı).', max_length=10),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='aylik_kullanim_bedeli',
            field=models.DecimalField(decimal_places=2, default=Decimal('3900.00'), help_text="Aylık e-İSA kullanım bedeli (TL). Demo'da faturalanmaz.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='durum',
            field=models.CharField(choices=[('TASLAK', 'Taslak'), ('AKTIF', 'Aktif'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL', 'İptal')], db_index=True, default='AKTIF', max_length=16),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='sozlesme_tipi_ay',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(12, '12 Ay'), (24, '24 Ay'), (36, '36 Ay')], help_text="Standart sözleşme süresi (ay). Demo'da boş.", null=True),
        ),
        migrations.CreateModel(
            name='SozlesmeUzatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('ek_ay', models.PositiveSmallIntegerField(blank=True, help_text='Eklenen ay (standart sözleşme).', null=True)),
                ('ek_gun', models.PositiveSmallIntegerField(blank=True, help_text='Eklenen gün (demo sözleşme).', null=True)),
                ('neden', models.CharField(blank=True, default='', max_length=255)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sozlesme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uzatmalar', to='abonelik.sozlesme')),
            ],
            options={
                'verbose_name': 'Sözleşme Uzatma',
                'verbose_name_plural': 'Sözleşme Uzatmaları',
                'db_table': 'abonelik_sozlesme_uzatmalari',
                'ordering': ('-olusturulma_tarihi', '-id'),
            },
        ),
    ]
