# Generated by Django 5.2.16 on 2026-09-30 22:30

from django.db import migrations, models


def _legacy_durum_to_aktif(apps, schema_editor):
    """TASLAK/TAMAMLANDI gibi kaldırılan durumları AKTIF'e çeker (süresi dolmuşluk türetilir)."""
    Sozlesme = apps.get_model("abonelik", "Sozlesme")
    Sozlesme.objects.exclude(durum__in=["AKTIF", "IPTAL"]).update(durum="AKTIF")


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0003_sozlesme_demo_gun_sozlesme_ek_ay_toplam_and_more'),
    ]

    operations = [
        migrations.RunPython(_legacy_durum_to_aktif, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sozlesme',
            name='durum',
            field=models.CharField(choices=[('AKTIF', 'Aktif'), ('IPTAL', 'İptal')], db_index=True, default='AKTIF', max_length=16),
        ),
    ]
