# Generated by Django 5.2.16 on 2026-09-30 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0004_alter_sozlesme_durum'),
        ('pharmacies', '0016_kiosk_build_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SozlesmeTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('talep_tipi', models.CharField(choices=[('YENI', 'Yeni Sözleşme'), ('UZATMA', 'Uzatma'), ('IPTAL', 'İptal')], db_index=True, max_length=10)),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], db_index=True, default='BEKLIYOR', max_length=12)),
                ('istenen_tur', models.CharField(blank=True, choices=[('DEMO', 'Demo'), ('STANDART', 'Standart')], default='', max_length=10)),
                ('istenen_tip_ay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('istenen_demo_gun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ek_ay', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ek_gun', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aciklama', models.CharField(blank=True, default='', max_length=500)),
                ('red_nedeni', models.CharField(blank=True, default='', max_length=500)),
                ('karar_tarihi', models.DateTimeField(blank=True, null=True)),
                ('eczane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sozlesme_talepleri', to='pharmacies.eczane')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hedef_sozlesme', models.ForeignKey(blank=True, help_text='Uzatma/iptal için ilgili sözleşme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talepler', to='abonelik.sozlesme')),
                ('karar_veren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusan_sozlesme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='abonelik.sozlesme')),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sözleşme Talebi',
                'verbose_name_plural': 'Sözleşme Talepleri',
                'db_table': 'abonelik_sozlesme_talepleri',
                'ordering': ('-olusturulma_tarihi', '-id'),
            },
        ),
    ]
