# Generated by Django 5.2.16 on 2026-09-30 23:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0005_sozlesmetalebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='cihaz_durumu',
            field=models.CharField(choices=[('SATILIK', 'Satılık'), ('KIRALIK', 'Kiralık')], default='SATILIK', help_text='Cihaz satılık mı kiralık mı?', max_length=12),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='cihaz_kira_bedeli',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kiralık cihaz için aylık kira bedeli (TL).', max_digits=12),
        ),
    ]
