# Generated by Django 5.2.16 on 2026-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0006_sozlesme_cihaz_durumu_sozlesme_cihaz_kira_bedeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesmeuzatma',
            name='is_iptal',
            field=models.BooleanField(default=False, help_text='Bu satır bir iptal işlemi mi?'),
        ),
        migrations.AddField(
            model_name='sozlesmeuzatma',
            name='iptal_nedeni',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]