# Generated by Django 5.2.16 on 2026-10-01 00:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0007_sozlesmeuzatma_is_iptal_iptal_nedeni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='tip',
            field=models.CharField(choices=[('KULLANIM_BEDELI', 'Kullanım Bedeli'), ('CIHAZ_TAKSIT', 'Cihaz Taksiti'), ('CIHAZ_KIRA', 'Cihaz Kira Bedeli')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='FiyatTanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('abonelik_bedeli', models.DecimalField(decimal_places=2, default=Decimal('3900.00'), help_text='Aylık e-İSA abonelik (kullanım) bedeli (TL).', max_digits=12)),
                ('cihaz_kira_bedeli', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kiralık cihaz için aylık kira bedeli (TL).', max_digits=12)),
                ('gecerlilik_baslangic', models.DateField(db_index=True, help_text='Bu fiyatın geçerli olmaya başladığı tarih.')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255)),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiyat Tanımı',
                'verbose_name_plural': 'Fiyat Tanımları',
                'db_table': 'abonelik_fiyat_tanimlari',
                'ordering': ('-gecerlilik_baslangic', '-id'),
            },
        ),
    ]
