# Generated by Django 5.2.16 on 2026-10-02 11:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0008_alter_fatura_tip_fiyattanimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='eczaci_onay_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Onay IP adresi.', null=True),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='eczaci_onay_tarihi',
            field=models.DateTimeField(blank=True, help_text='Eczacının dijital onay tarihi.', null=True),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='iptal_ceza_orani',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Erken iptal ceza oranı (%): kalan aylık bedellerinin bu yüzdesi ceza.', max_digits=5),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='kdv_orani',
            field=models.PositiveSmallIntegerField(choices=[(0, '%0 (KDV Yok)'), (1, '%1'), (10, '%10'), (20, '%20')], default=0, help_text='Kullanım bedeli ve cihaz kira üzerindeki KDV oranı (%).'),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='tevkifat_orani',
            field=models.CharField(blank=True, choices=[('', 'Yok'), ('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10')], default='', help_text="KDV tevkifat oranı (ör. '3/10'). Boş = tevkifat yok.", max_length=4),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='taksit_sayisi',
            field=models.PositiveSmallIntegerField(default=4, help_text='Taksit sayısı (1–12).'),
        ),
    ]
