# Generated by Django 5.2.16 on 2026-10-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0009_sozlesme_eczaci_onay_ip_sozlesme_eczaci_onay_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihazodemeplani',
            name='adet',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cihaz adedi (bu plan kaptağı).'),
        ),
        migrations.AddField(
            model_name='cihazodemeplani',
            name='cihaz_kdv_orani',
            field=models.PositiveSmallIntegerField(choices=[(0, '%0 (KDV Yok)'), (1, '%1'), (10, '%10'), (20, '%20')], default=0, help_text='Cihaz satışı üzerinden KDV oranı (%).'),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='pesin_fiyat',
            field=models.DecimalField(decimal_places=2, help_text='Birim cihaz peşin fiyatı (TL).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='sozlesme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cihaz_planlari', to='abonelik.sozlesme'),
        ),
    ]
