# Generated by Django 5.2.16 on 2026-10-02 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0010_cihazodemeplani_adet_cihazodemeplani_cihaz_kdv_orani_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihazodemeplani',
            name='aylik_kira_bedeli',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Birim aylık kira bedeli (TL). Kiralıkta zorunlu.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cihazodemeplani',
            name='tevkifat_orani',
            field=models.CharField(blank=True, choices=[('', 'Yok'), ('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10')], default='', help_text='KDV tevkifat oranı.', max_length=4),
        ),
        migrations.AddField(
            model_name='cihazodemeplani',
            name='tip',
            field=models.CharField(choices=[('SATILIK', 'Satılık'), ('KIRALIK', 'Kiralık')], default='SATILIK', help_text='Satılık (peşin+taksit) veya kiralık (aylık kira).', max_length=8),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='adet',
            field=models.PositiveSmallIntegerField(default=1, help_text='Cihaz adedi.'),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='baslangic_tarihi',
            field=models.DateField(help_text='İlk faturalandırma ayı.'),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='cihaz_kdv_orani',
            field=models.PositiveSmallIntegerField(choices=[(0, '%0 (KDV Yok)'), (1, '%1'), (10, '%10'), (20, '%20')], default=0, help_text='KDV oranı (%).'),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='pesin_fiyat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Birim peşin fiyat (TL). Satılıkta zorunlu.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='taksit_sayisi',
            field=models.PositiveSmallIntegerField(default=1, help_text='Taksit sayısı (1–12).'),
        ),
        migrations.AlterField(
            model_name='cihazodemeplani',
            name='vade_farki_orani',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Vade farkı yüzde (%).', max_digits=6),
        ),
    ]
