# Generated by Django 5.2.16 on 2026-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0011_cihazodemeplani_aylik_kira_bedeli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='aciklama',
            field=models.CharField(blank=True, default='', help_text='Ödeme açıklaması / referans bilgisi. Manuel ödemelerde zorunludur.', max_length=500),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='imza_tipi',
            field=models.CharField(choices=[('DIJITAL', 'Dijital İmza'), ('ISLAK', 'Islak İmza')], default='DIJITAL', help_text='Dijital (eczacı ekrandan onaylar) veya ıslak (taranıp yüklenir).', max_length=8),
        ),
        migrations.AddField(
            model_name='sozlesme',
            name='islak_imza_url',
            field=models.CharField(blank=True, default='', help_text='RustFS/S3 yolu — ıslak imzalı belge (expiring URL değil, kalıcı path).', max_length=500),
        ),
        migrations.AlterField(
            model_name='odeme',
            name='yontem',
            field=models.CharField(choices=[('KREDI_KARTI', 'Kredi Kartı'), ('EFT_HAVALE', 'EFT/Havale'), ('OTOMATIK_CEKIM', 'Otomatik Çekim'), ('MANUEL', 'Manuel')], default='KREDI_KARTI', max_length=16),
        ),
    ]
