# Generated by Django 5.2.16 on 2026-10-02 14:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0012_odeme_aciklama_sozlesme_imza_tipi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fiyattanimi',
            name='acma_kapama_bedeli',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hesap açma/kapama bedeli: gecikme sonrası yeniden aktifleştirme ücreti (TL).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tip',
            field=models.CharField(choices=[('KULLANIM_BEDELI', 'Kullanım Bedeli'), ('CIHAZ_TAKSIT', 'Cihaz Taksiti'), ('CIHAZ_KIRA', 'Cihaz Kira Bedeli'), ('BIRLESIK', 'Birleşik Aylık Fatura'), ('ACMA_KAPAMA', 'Açma/Kapama Bedeli')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sozlesme',
            name='iptal_ceza_orani',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Erken iptal ceza katsayısı: ceza = kalan_ay × katsayi × aylık_bedel. Varsayılan 2.', max_digits=5),
        ),
        migrations.CreateModel(
            name='FaturaKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('surum', models.PositiveIntegerField(default=1, editable=False)),
                ('tip', models.CharField(choices=[('ABONELIK', 'Abonelik Bedeli'), ('CIHAZ_TAKSIT', 'Cihaz Taksiti'), ('CIHAZ_KIRA', 'Cihaz Kira'), ('ACMA_KAPAMA', 'Açma/Kapama')], max_length=20)),
                ('taksit_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aciklama', models.CharField(blank=True, default='', max_length=255)),
                ('cihaz_plani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatura_kalemleri', to='abonelik.cihazodemeplani')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='abonelik.fatura')),
                ('guncelleyen', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura Kalemi',
                'verbose_name_plural': 'Fatura Kalemleri',
                'db_table': 'abonelik_fatura_kalemleri',
                'ordering': ('id',),
            },
        ),
    ]
