# Generated by Django 5.2.16 on 2026-10-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0013_fiyattanimi_acma_kapama_bedeli_alter_fatura_tip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozlesme',
            name='onayli_sozlesme_metni',
            field=models.TextField(blank=True, default='', help_text='Dijital onay anındaki tam sözleşme metni (HTML). Onaylandıktan sonra değişmez.'),
        ),
    ]
