# Generated by Django 5.2.16 on 2026-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0015_fiyattanimi_iptal_ceza_orani'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihazodemeplani',
            name='oteleme_ay',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cihaz öteleme süresi (ay). Abonelikten bağımsızdır; ilk cihaz faturası sözleşme başlangıcı + bu kadar ay sonra kesilir. 0 ise sözleşme tarihiyle aynı.'),
        ),
    ]
