# Generated by Django 5.2.16 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonelik', '0016_cihazodemeplani_oteleme_ay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihazodemeplani',
            name='cihaz_bilgisi',
            field=models.CharField(blank=True, default='', help_text='Cihaz tanımı / marka-model / açıklama; manuel olarak girilebilir.', max_length=255),
        ),
    ]
