# Generated by Django 5.2 on 2026-08-11

import django.core.validators
import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pharmacies", "0010_kiosk_eczane_kiosk_no"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BarkodLogo",
            fields=[
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("guncellenme_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "guncelleyen",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("surum", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ad", models.CharField(max_length=255)),
                ("media_url", models.CharField(blank=True, default="", max_length=2048)),
                ("object_key", models.CharField(blank=True, default="", max_length=1024)),
                ("checksum", models.CharField(blank=True, default="", max_length=80)),
                ("baslangic_zamani", models.DateTimeField()),
                ("bitis_zamani", models.DateTimeField()),
                ("aktif", models.BooleanField(db_index=True, default=True)),
                (
                    "gunluk_baski_limiti",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "hedef_kiosklar",
                    models.ManyToManyField(
                        blank=True,
                        related_name="barkod_logolar",
                        to="pharmacies.kiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barkod Logo",
                "verbose_name_plural": "Barkod Logolar",
                "db_table": "barkod_logolar",
                "ordering": ("olusturulma_tarihi", "id"),
            },
        ),
    ]
