# Generated by Django 5.2.16 on 2026-08-11 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkod_logo', '0001_initial'),
        ('pharmacies', '0010_kiosk_eczane_kiosk_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barkodlogo',
            name='aktif',
            field=models.BooleanField(db_index=True, default=True, help_text='Pasif logolar bir sonraki başarılı katalog senkronizasyonundan sonra rotasyondan çıkar.'),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='baslangic_zamani',
            field=models.DateTimeField(help_text='Logo rotasyonunun başlayacağı UTC zaman.'),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='bitis_zamani',
            field=models.DateTimeField(help_text='Logo rotasyonunun sona ereceği UTC zaman (bu an dahil DEĞİL).'),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='sha256:<hex> formatında dosya özeti.', max_length=80),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='gunluk_baski_limiti',
            field=models.PositiveIntegerField(blank=True, help_text='Her bir kioskta, bir takvim günü içinde yapılabilecek en fazla baskı sayısıdır. Boş bırakılırsa sınırsızdır.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='hedef_kiosklar',
            field=models.ManyToManyField(blank=True, help_text='Bu logoyu alacak kiosklar. Boş bırakılırsa hiçbir kioska dağıtılmaz.', related_name='barkod_logolar', to='pharmacies.kiosk'),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='media_url',
            field=models.CharField(blank=True, default='', help_text="Görselin kalıcı public URL'si.", max_length=2048),
        ),
        migrations.AlterField(
            model_name='barkodlogo',
            name='object_key',
            field=models.CharField(blank=True, default='', help_text='RustFS/S3 nesne anahtarı.', max_length=1024),
        ),
    ]
